### ISSUE TITLE
Server 2016 Nano support

### ISSUE THREAD

**Issue by WarrenSchultz** [dvdstore/ds3#2]
If it is possible, it would be appreciated if the DS3 SQL drivers could be recompiled in 64 bit, for compatibility with Windows Server 2016 Nano installs.

**Comment by toddmuirhead** [comment]
I think that the SQL Server driver is compiled with 64 bit .Net, but the version of .Net on Windows Server 2016 Nano is probably more recent.  Anyway - it is easy to recompile the driver program. You just need the c sharp compiler which is csc.exe for the version of .Net that you are using.  The complete command for compiling the driver is in the header of the dsxdriver.cs file.  Following that example the command for the SQL Server driver is:
csc /out:ds3sqlserverdriver.exe ds3xdriver.cs ds3sqlserverfns.cs /d:USE_WIN32_TIMER /d:GEN_PERF_CTRS

If you don't want to use the high resolution win32 timers or the windows performance counters, then just leave those two /d options off of the end of the csc compile command.

Let me know if you have any problems.  It's really interesting to hear that you are running it on the Nano version of Windows Server 2016.

Thanks - Todd

**Comment by toddmuirhead** [comment]
Closing.....
