### ISSUE TITLE
Error accessing server machine

### ISSUE THREAD

**Issue by fraziermatthew** [dvdstore/ds3#5]
I've installed ds2 on a AWS AMI EC2 instance to host the server with a MySQL database. I've successfully loaded the data into the database. For the client, I've launched another Linux Centos EC2 instance in AWS and successfully confirmed that I can access the mysql database from the server machine.

To compile the .exe file, I've installed Mono and have successfully compiled the program. However, when running the program, I am getting the following error: 

[root@ip-172-31-36-226 drivers]# mono ds2mysqldriver.exe --target=172.31.46.171
Total number of Threads to be Spawned across multiple servers are n_threads: 1
target= 172.31.46.171  n_threads= 1  ramp_rate= 10  run_time= 0  db_size= 10MB  warmup_time= 1  think_time= 0
pct_newcustomers= 20  n_searches= 3  search_batch_size= 5  n_line_items= 5  virt_dir= ds2  page_type= php  windows_perf_host=  detailed_view= N linux_perf_host=

Using WIN32 QueryPerformanceCounters for measuring response time

Performance Counter Category Test and Counters MaxRT and OPM created

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'ds2xdriver.ds2Interface:objConn' (1) due to: Could not load file or assembly 'MySql.Data, Version=6.3.6.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its dependencies. assembly:MySql.Data, Version=6.3.6.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d type:<unknown type> member:(null) signature:<none>
  at ds2xdriver.Controller..ctor (System.String[] argarray) [0x00f1d] in <b673ecf65687451c85ceb99a469bce45>:0
  at ds2xdriver.Controller.Main (System.String[] args) [0x00001] in <b673ecf65687451c85ceb99a469bce45>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'ds2xdriver.ds2Interface:objConn' (1) due to: Could not load file or assembly 'MySql.Data, Version=6.3.6.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its dependencies. assembly:MySql.Data, Version=6.3.6.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d type:<unknown type> member:(null) signature:<none>
  at ds2xdriver.Controller..ctor (System.String[] argarray) [0x00f1d] in <b673ecf65687451c85ceb99a469bce45>:0
  at ds2xdriver.Controller.Main (System.String[] args) [0x00001] in <b673ecf65687451c85ceb99a469bce45>:0

I cannot understand what is preventing the program from running because I was able to access the MySQL database from the server using the -h <host> parameter. Any help is appreciated in effort to resolve this.
Thanks!

**Comment by toddmuirhead** [comment]
Matthew,

The error is in reference to the MySQL.Data.dll not being available.  This
is the library for the MySQL .Net connector.  It looks like it is
specifically looking for version 6.3.6.  You can download the MySQL .Net
Connector from the MySQL site -
https://dev.mysql.com/downloads/connector/net/

Normally, when you compile the driver program on windows with the csc.exe c
sharp compiler, you specify the location of this .dll in the compile string
as a resource with the /r parameter:
csc /out:ds3mysqldriver.exe     ds3xdriver.cs ds3mysqlfns.cs
/d:USE_WIN32_TIMER /d:GEN_PERF_CTRS  /r:<path>MySql.Data.dll

Make sure that the same version of the MySQL .Net connection library -
MySQL.Data.dll - that you used to compile with is available on your linux
client environment.

Let me know if you have any other questions or issues.

Thanks,
Todd

**Comment by fraziermatthew** [comment]
Thanks for the fast reply and the tip! I was able to compile with the 6.3.6.0 driver and next ran into this error. Is this related to another /r parameter needed that I need to add at compile time?

[root@ip-172-31-36-226 drivers]# mono ds2mysqldriver.exe --target=172.31.46.171
Total number of Threads to be Spawned across multiple servers are n_threads: 1
target= 172.31.46.171  n_threads= 1  ramp_rate= 10  run_time= 0  db_size= 10MB  warmup_time= 1  think_time= 0
pct_newcustomers= 20  n_searches= 3  search_batch_size= 5  n_line_items= 5  virt_dir= ds2  page_type= php  windows_perf_host=  detailed_view= N linux_perf_host=

Using WIN32 QueryPerformanceCounters for measuring response time

Performance Counter Category Test and Counters MaxRT and OPM created
Thread 0: created for User 0
Thread 0: connected to 172.31.46.171
Controller (2/10/2020 6:02:53 PM): all threads running
Controller (2/10/2020 6:02:53 PM): all threads connected - issuing Start

Unhandled Exception:
System.EntryPointNotFoundException: QueryPerformanceFrequency
  at (wrapper managed-to-native) ds2xdriver.Controller.QueryPerformanceFrequency(long&)
  at ds2xdriver.Controller..ctor (System.String[] argarray) [0x0116a] in <a68a4065bf744525af86e8e3b2c9138b>:0
  at ds2xdriver.Controller.Main (System.String[] args) [0x00001] in <a68a4065bf744525af86e8e3b2c9138b>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.EntryPointNotFoundException: QueryPerformanceFrequency
  at (wrapper managed-to-native) ds2xdriver.Controller.QueryPerformanceFrequency(long&)
  at ds2xdriver.Controller..ctor (System.String[] argarray) [0x0116a] in <a68a4065bf744525af86e8e3b2c9138b>:0
  at ds2xdriver.Controller.Main (System.String[] args) [0x00001] in <a68a4065bf744525af86e8e3b2c9138b>:0

**Comment by toddmuirhead** [comment]
Matthew,

When running in mono I don't think that the windows specific stuff will
work - like perfmon counter and win32 timing.  I think that you need to
leave those two /d parameters off when you do the compile for a mono run.
The error that you are getting is basically an error that linux mono
doesn't have the library for windows performance monitor.

I haven't done a mono compile in a little while, so I'm a bit rusty on this
side of things.  Let me know if you are still having problems.

Thanks,
Todd

**Comment by fraziermatthew** [comment]
Thanks! I was able to get this to run by updating 2 things: (1) I was missing a System.Data.dll file that was needed for compiling and (2) Adding authorized_keys so that my client could access the server.
