### ISSUE TITLE
Running on multiple SQL servers

### ISSUE THREAD

**Issue by ajayvaaka** [dvdstore/ds3#9]
Hi Team,

I'm able to run ds3 on single SQL instance , i have issue with running on multiple SQL targets . Can i get pre-requirement setup for multiple SQL server run please. 

Command : 
.\sqlserverds3\ds3sqlserverdriver.exe --target=10.1.11.22;10.1.11.21 --log_timestamp=LOCAL --n_threads=8 --ramp_rate=10 --run_time=5 --db_size=10MB --warmup_time=0 --think_time=0.085 --n_searches=3 --search_batch_size=5 --n_line_items=5 --windows_perf_host=10.1.11.22;10.1.11.21 --detailed_view=Y --out_filename=testresults1.txt

issue : 
![image](https://user-images.githubusercontent.com/17277729/167168682-7313a486-e2b5-430b-8a32-04ba770449b4.png)

able to communicate with one server (localhost) , not with another SQL server.

Thanks & Regards
Ajay Vaaka

**Comment by toddmuirhead** [comment]
Ajay,

Try running against each of the hosts individually to verify that all
firewall / network access is good.  If it isn't working going to the remote
DB, then you need to check that the firewall is not preventing access.
Also check to make sure that SQL Server is allowing remote connections and
the TCP/IP transport for SQL Server is enabled.

Thanks,
Todd

**Comment by ajayvaaka** [comment]
Try running against each of the hosts individually to verify that all firewall / network access is good: **yes it is good**
* Running on local sql server ; failed to connect to another sql server<img width="490" alt="1" src="https://user-images.githubusercontent.com/17277729/167454495-c336724b-37f1-4431-b358-d33e08b774af.PNG">

check to make sure that SQL Server is allowing remote connections : **It is good**
* It is good already
<img width="762" alt="2" src="https://user-images.githubusercontent.com/17277729/167454634-8ce47a39-6aca-40b1-b7a8-e0f6a99a9bbe.PNG">

TCP/IP transport for SQL Server is enabled: **enabled**

* It is good already

<img width="388" alt="4" src="https://user-images.githubusercontent.com/17277729/167455638-11c833bd-70e9-457b-b99d-a936a681a3b4.PNG">


still no luck.

FYI: i have these SQL servers installed as standalone. please let me know, it needs to be changed

Thanks & Regards
Ajay Vaaka

**Comment by toddmuirhead** [comment]
Ajay,

I tried out your exact command (except for with IPs that represent my VMs)
and was able to run successfully.  I don't often use some of these options
and so I wanted make sure that there wasn't something strange going on when
they were all used together - and it worked on my setup.  So this is a good
sign!

I'm not completely clear on what you have tried and what worked and what
did not.  In the screenshots that you sent, you only show successful
connections to 10.1.11.22.  If you run the driver with --target=10.1.11.21
- does that work?

Thanks,
Todd

**Comment by ajayvaaka** [comment]
when i'm on 10.1.11.22 server : it is connecting to itself and not able to connect to neighbour server 10.1.11.21 and vice versa.

**Comment by toddmuirhead** [comment]
It is likely a SQL Server configuration issue or a firewall configuration
manager:

Check you SQL Server configuration:
[image: image.png]

If this is in a test environment you can just disable the windows
firewall.  If not a test environment, you will need to open up the firewall
to allow sql server client to connect:
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-windows-firewall-for-database-engine-access?view=sql-server-ver15


Let me know how it goes.

Thanks,
Todd

**Comment by ajayvaaka** [comment]
Thanks Todd , firewall changes did the trick.
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-windows-firewall-for-database-engine-access?view=sql-server-ver15 : worked

Thanks for the continuous support
